import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import {
  createBusinessCatalogItem, createBusinessPromotion, deleteBusinessCatalogItem,
  deleteBusinessPromotion, getBusinessCatalog, getBusinessCommerceDashboard,
  getBusinessInquiries, getBusinessPromotions, getBusinessReservations,
  shareBusinessCatalogItem, shareBusinessPromotion, updateBusinessCatalogItem,
  updateBusinessInquiry, updateBusinessPromotion, updateBusinessReservationStatus,
} from '../services/api'
import { CatalogCard, PromotionCard } from '../components/commerce/CommerceCards'
import VetPawLoader from '../components/VetPawLoader'
import './BusinessCommerce.css'

const categories = [['grooming','Peluquería'],['food','Alimentos'],['accessories','Accesorios'],['daycare','Guardería'],['boarding','Hospedaje'],['walking','Paseos'],['training','Adiestramiento'],['transport','Transporte'],['pharmacy','Farmacia e higiene'],['photography','Fotografía'],['other','Otro']]
const emptyItem = { item_type:'service', category:'grooming', title:'', description:'', price:'', price_on_request:false, promotional_price:'', species:['dog'], duration_minutes:60, requires_booking:true, home_service:false, delivery:false, pickup:false, stock_quantity:'', is_active:true }
const localDateTime = offset => { const d=new Date(Date.now()+offset); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16) }
const emptyPromotion = { catalog_item:'', title:'', description:'', previous_price:'', promotional_price:'', starts_at:localDateTime(0), ends_at:localDateTime(7*86400000), quantity_available:'', locality:'', is_active:true }

export default function BusinessCommerce() {
  const [params, setParams] = useSearchParams()
  const tab = params.get('tab') || 'resumen'
  const [dashboard,setDashboard]=useState(null), [items,setItems]=useState([]), [promotions,setPromotions]=useState([]), [reservations,setReservations]=useState([]), [inquiries,setInquiries]=useState([])
  const [loading,setLoading]=useState(true), [error,setError]=useState(''), [message,setMessage]=useState('')
  const [itemForm,setItemForm]=useState(emptyItem), [itemId,setItemId]=useState(null), [promotionForm,setPromotionForm]=useState(emptyPromotion), [promotionId,setPromotionId]=useState(null)

  const load=useCallback(async()=>{ setLoading(true); setError(''); try { const [d,c,p,r,i]=await Promise.all([getBusinessCommerceDashboard(),getBusinessCatalog({mine:true}),getBusinessPromotions({mine:true}),getBusinessReservations(),getBusinessInquiries()]); setDashboard(d); setItems(c); setPromotions(p); setReservations(r); setInquiries(i) } catch(e){ setError(e.response?.data?.detail||'No pudimos cargar el panel comercial.') } finally { setLoading(false) } },[])
  useEffect(()=>{ load() },[load])
  const setTab=next=>setParams(next==='resumen'?{}:{tab:next})
  const resetItem=()=>{setItemForm(emptyItem);setItemId(null)}
  const resetPromotion=()=>{setPromotionForm(emptyPromotion);setPromotionId(null)}
  const saveItem=async e=>{e.preventDefault();setError('');try{const payload={...itemForm};if(itemForm.image instanceof File)payload.image=itemForm.image;const saved=itemId?await updateBusinessCatalogItem(itemId,payload):await createBusinessCatalogItem(payload);setMessage(itemId?'Elemento actualizado.':'Elemento agregado al catálogo.');setItems(current=>itemId?current.map(x=>x.id===saved.id?saved:x):[saved,...current]);resetItem()}catch(err){setError(JSON.stringify(err.response?.data||'No se pudo guardar.'))}}
  const editItem=item=>{setItemId(item.id);setItemForm({...item,image:null});setTab('catalogo');window.scrollTo({top:0,behavior:'smooth'})}
  const removeItem=async id=>{if(!window.confirm('¿Eliminar este elemento del catálogo?'))return;await deleteBusinessCatalogItem(id);setItems(current=>current.filter(x=>x.id!==id))}
  const savePromotion=async e=>{e.preventDefault();setError('');try{const payload={...promotionForm,catalog_item:promotionForm.catalog_item||null};if(promotionForm.image instanceof File)payload.image=promotionForm.image;const saved=promotionId?await updateBusinessPromotion(promotionId,payload):await createBusinessPromotion(payload);setMessage(promotionId?'Promoción actualizada.':'Promoción creada.');setPromotions(current=>promotionId?current.map(x=>x.id===saved.id?saved:x):[saved,...current]);resetPromotion()}catch(err){setError(JSON.stringify(err.response?.data||'No se pudo guardar.'))}}
  const editPromotion=promotion=>{setPromotionId(promotion.id);setPromotionForm({...promotion,starts_at:String(promotion.starts_at).slice(0,16),ends_at:String(promotion.ends_at).slice(0,16),image:null});setTab('promociones');window.scrollTo({top:0,behavior:'smooth'})}
  const removePromotion=async id=>{if(!window.confirm('¿Eliminar esta promoción?'))return;await deleteBusinessPromotion(id);setPromotions(current=>current.filter(x=>x.id!==id))}
  const changeReservation=async(id,status)=>{const updated=await updateBusinessReservationStatus(id,{status});setReservations(current=>current.map(x=>x.id===id?updated:x))}
  const changeInquiry=async(id,status)=>{const updated=await updateBusinessInquiry(id,status);setInquiries(current=>current.map(x=>x.id===id?updated:x))}
  const stats=dashboard?.stats||{}
  const activeServices=useMemo(()=>items.filter(x=>x.item_type==='service'&&x.requires_booking),[items])
  if(loading)return <VetPawLoader message="Cargando panel comercial..." subText="Preparando catálogo y reservas" />
  return <main className="commerce-page"><div className="commerce-shell">
    <header className="commerce-hero"><div><span>🛍️ VETPAW NEGOCIOS</span><h1>Panel comercial</h1><p>Administrá tu catálogo, promociones, consultas y reservas sin salir de VetPaw.</p></div><div className="commerce-access"><b>{dashboard?.access?.status_display}</b><small>Acceso completo durante el desarrollo</small><Link to={`/negocios/${dashboard?.business?.slug}`}>Ver perfil público</Link></div></header>
    <nav className="commerce-tabs">{[['resumen','📊 Resumen'],['catalogo','🛍️ Catálogo'],['promociones','🎁 Promociones'],['reservas','📅 Reservas'],['consultas','💬 Consultas']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {error&&<div className="commerce-alert error">{error}</div>}{message&&<div className="commerce-alert">{message}</div>}
    {tab==='resumen'&&<><section className="commerce-stats">{[['Visitas',stats.profile_views],['Catálogo',stats.catalog_items],['Promociones',stats.promotions_active],['Favoritos',stats.favorites],['Consultas nuevas',stats.inquiries_new],['Reservas pendientes',stats.reservations_pending]].map(([label,value])=><article key={label}><strong>{value||0}</strong><span>{label}</span></article>)}</section><section className="commerce-panel"><h2>Próximas reservas</h2>{dashboard?.upcoming_reservations?.length?dashboard.upcoming_reservations.map(r=><ReservationRow key={r.id} reservation={r} onChange={changeReservation}/>):<p className="commerce-empty">Todavía no hay reservas próximas.</p>}</section></>}
    {tab==='catalogo'&&<><CommerceItemForm form={itemForm} setForm={setItemForm} onSubmit={saveItem} editing={Boolean(itemId)} onCancel={resetItem}/><section className="commerce-grid">{items.map(item=><CatalogCard key={item.id} item={item} ownerActions={<><button type="button" onClick={()=>editItem(item)}>Editar</button><button type="button" onClick={()=>shareBusinessCatalogItem(item.id)}>Compartir</button><button type="button" className="danger" onClick={()=>removeItem(item.id)}>Eliminar</button></>}/>)}</section></>}
    {tab==='promociones'&&<><PromotionForm form={promotionForm} setForm={setPromotionForm} items={items} onSubmit={savePromotion} editing={Boolean(promotionId)} onCancel={resetPromotion}/><section className="commerce-grid">{promotions.map(p=><PromotionCard key={p.id} promotion={p} ownerActions={<><button type="button" onClick={()=>editPromotion(p)}>Editar</button><button type="button" onClick={()=>shareBusinessPromotion(p.id)}>Compartir</button><button type="button" className="danger" onClick={()=>removePromotion(p.id)}>Eliminar</button></>}/>)}</section></>}
    {tab==='reservas'&&<section className="commerce-panel"><h2>Reservas recibidas</h2>{reservations.length?reservations.map(r=><ReservationRow key={r.id} reservation={r} onChange={changeReservation}/>):<p className="commerce-empty">Todavía no recibiste reservas. Activá reservas en tu perfil y en un servicio.</p>} {!activeServices.length&&<p className="commerce-hint">Creá un servicio con “Permitir reservas” para empezar.</p>}</section>}
    {tab==='consultas'&&<section className="commerce-panel"><h2>Consultas recibidas</h2>{inquiries.length?inquiries.map(i=><article className="commerce-row" key={i.id}><div><b>{i.user_name}</b><span>{i.catalog_item_title||i.promotion_title||i.business_name}</span><p>{i.content}</p></div><div><select value={i.status} onChange={e=>changeInquiry(i.id,e.target.value)}><option value="new">Nueva</option><option value="replied">Respondida</option><option value="closed">Cerrada</option></select><Link to="/messages">Abrir mensajes</Link></div></article>):<p className="commerce-empty">Todavía no hay consultas.</p>}</section>}
  </div></main>
}

function CommerceItemForm({form,setForm,onSubmit,editing,onCancel}){const set=(k,v)=>setForm(c=>({...c,[k]:v}));return <form className="commerce-form" onSubmit={onSubmit}><h2>{editing?'Editar elemento':'Agregar producto o servicio'}</h2><div className="commerce-form-grid"><label>Tipo<select value={form.item_type} onChange={e=>set('item_type',e.target.value)}><option value="service">Servicio</option><option value="product">Producto</option></select></label><label>Categoría<select value={form.category} onChange={e=>set('category',e.target.value)}>{categories.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="wide">Nombre<input required value={form.title} onChange={e=>set('title',e.target.value)}/></label><label className="wide">Descripción<textarea required value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Precio<input type="number" min="0" value={form.price} onChange={e=>set('price',e.target.value)}/></label><label>Precio promocional<input type="number" min="0" value={form.promotional_price||''} onChange={e=>set('promotional_price',e.target.value)}/></label><label>Foto<input type="file" accept="image/*" onChange={e=>set('image',e.target.files?.[0]||null)}/></label>{form.item_type==='service'&&<label>Duración en minutos<input type="number" min="15" value={form.duration_minutes||''} onChange={e=>set('duration_minutes',e.target.value)}/></label>}<div className="wide commerce-checks">{[['price_on_request','Consultar precio'],['requires_booking','Permitir reservas'],['home_service','A domicilio'],['delivery','Envíos'],['pickup','Retiro en local'],['is_active','Visible']].map(([k,l])=><label key={k}><input type="checkbox" checked={Boolean(form[k])} disabled={k==='requires_booking'&&form.item_type==='product'} onChange={e=>set(k,e.target.checked)}/>{l}</label>)}</div></div><div className="commerce-form-actions"><button>Guardar</button>{editing&&<button type="button" className="secondary" onClick={onCancel}>Cancelar edición</button>}</div></form>}
function PromotionForm({form,setForm,items,onSubmit,editing,onCancel}){const set=(k,v)=>setForm(c=>({...c,[k]:v}));return <form className="commerce-form" onSubmit={onSubmit}><h2>{editing?'Editar promoción':'Crear promoción'}</h2><div className="commerce-form-grid"><label className="wide">Producto o servicio relacionado<select value={form.catalog_item||''} onChange={e=>set('catalog_item',e.target.value)}><option value="">Sin vincular</option>{items.map(i=><option value={i.id} key={i.id}>{i.title}</option>)}</select></label><label className="wide">Título<input required value={form.title} onChange={e=>set('title',e.target.value)}/></label><label className="wide">Descripción<textarea required value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Precio anterior<input type="number" min="0" value={form.previous_price||''} onChange={e=>set('previous_price',e.target.value)}/></label><label>Precio promocional<input type="number" min="0" value={form.promotional_price||''} onChange={e=>set('promotional_price',e.target.value)}/></label><label>Inicio<input type="datetime-local" required value={form.starts_at} onChange={e=>set('starts_at',e.target.value)}/></label><label>Final<input type="datetime-local" required value={form.ends_at} onChange={e=>set('ends_at',e.target.value)}/></label><label>Foto<input type="file" accept="image/*" onChange={e=>set('image',e.target.files?.[0]||null)}/></label><label><input type="checkbox" checked={Boolean(form.is_active)} onChange={e=>set('is_active',e.target.checked)}/> Activa</label></div><div className="commerce-form-actions"><button>Guardar promoción</button>{editing&&<button type="button" className="secondary" onClick={onCancel}>Cancelar</button>}</div></form>}
function ReservationRow({reservation,onChange}){return <article className="commerce-row"><div><b>{reservation.pet_name} · {reservation.catalog_item_title}</b><span>{new Date(`${reservation.date}T${reservation.start_time}`).toLocaleString('es-AR',{dateStyle:'medium',timeStyle:'short'})}</span><p>{reservation.user_name} {reservation.user_phone&&`· ${reservation.user_phone}`}</p></div><div><strong className={`status ${reservation.status}`}>{reservation.status_display}</strong>{reservation.status==='pending'&&<><button onClick={()=>onChange(reservation.id,'confirmed')}>Confirmar</button><button className="danger" onClick={()=>onChange(reservation.id,'rejected')}>Rechazar</button></>}{reservation.status==='confirmed'&&<button onClick={()=>onChange(reservation.id,'completed')}>Completar</button>}</div></article>}
